apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: appoptics-agent-ds
  namespace: kube-system
  labels:
    daemon: appoptics-agent-ds
spec:
  template:
    metadata:
      name: appoptics-agent-ds
      labels:
        daemon: appoptics-agent-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: appoptics-agent-ds
        image: 'appoptics-agent-docker-local'
        imagePullPolicy: Never
        env:
          - name: APPOPTICS_TOKEN
            value: 'b686a827474ec1d4794a8bfb86af1e409456875e417bdfa925a5a6430eedcd88'
          - name: APPOPTICS_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APPOPTICS_ENABLE_DOCKER
            value: 'true'
          - name: HOST_PROC
            value: '/host/proc'
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
          - name: temp
            mountPath: /tmp/k8s
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: temp
          hostPath:
            path: /tmp/k8s
