collector:
  docker:
    all:
      # endpoint: "tcp://docker:2375"
      endpoint: "unix:///var/run/docker.sock"
      # procfs: "/proc"
      procfs: "/host/proc"

load:
  plugin: snap-plugin-collector-aodocker
  task: task-aodocker-stream.yaml
