---
version: 1

schedule:
  type: cron
  interval: "0 * * * * *"

deadline: "55s"

workflow:
  collect:

    metrics:
      /docker/*/container/count: {}
      /docker/*/container/paused: {}
      /docker/*/container/running: {}
      /docker/*/container/stopped: {}
      /docker/*/cpu/cpu_usage/total: {}
      /docker/*/cpu/cpu_usage/kernel_mode: {}
      /docker/*/cpu/cpu_usage/user_mode: {}
      /docker/*/cpu/cpu_usage/usage_percent: {}
      /docker/*/cpu/throttling_data/nr_periods: {}
      /docker/*/cpu/throttling_data/nr_throttled: {}
      /docker/*/cpu/throttling_data/throttled_time: {}
      /docker/*/memory/usage/max_usage: {}
      /docker/*/memory/usage/usage_percent: {}
      /docker/*/memory/statistics/active_anon: {}
      /docker/*/memory/statistics/active_file: {}
      /docker/*/memory/statistics/cache: {}
      /docker/*/memory/statistics/hierarchical_memory_limit: {}
      /docker/*/memory/statistics/inactive_anon: {}
      /docker/*/memory/statistics/inactive_file: {}
      /docker/*/memory/statistics/mapped_file: {}
      /docker/*/memory/statistics/pgfault: {}
      /docker/*/memory/statistics/pgmajfault: {}
      /docker/*/memory/statistics/pgpgin: {}
      /docker/*/memory/statistics/pgpgout: {}
      /docker/*/memory/statistics/rss: {}
      /docker/*/memory/statistics/rss_huge: {}
      /docker/*/blkio/io_service_bytes_recursive/*: {}
      /docker/*/blkio/io_serviced_recursive/*: {}
      /docker/*/network/*/rx_bytes: {}
      /docker/*/network/*/rx_dropped: {}
      /docker/*/network/*/rx_errors: {}
      /docker/*/network/*/rx_packets: {}
      /docker/*/network/*/tx_bytes: {}
      /docker/*/network/*/tx_dropped: {}
      /docker/*/network/*/tx_errors: {}
      /docker/*/network/*/tx_packets: {}
      # All available metrics
      #/docker/*/blkio/io_service_bytes_recursive/*/read: {}
      #/docker/*/blkio/io_service_bytes_recursive/*/write: {}
      #/docker/*/blkio/io_service_bytes_recursive/*/sync: {}
      #/docker/*/blkio/io_service_bytes_recursive/*/async: {}
      #/docker/*/blkio/io_service_bytes_recursive/*/total: {}
      #/docker/*/blkio/io_serviced_recursive/*/read: {}
      #/docker/*/blkio/io_serviced_recursive/*/write: {}
      #/docker/*/blkio/io_serviced_recursive/*/sync: {}
      #/docker/*/blkio/io_serviced_recursive/*/async: {}
      #/docker/*/blkio/io_serviced_recursive/*/total: {}
      #/docker/*/blkio/io_queue_recursive/*/read: {}
      #/docker/*/blkio/io_queue_recursive/*/write: {}
      #/docker/*/blkio/io_queue_recursive/*/sync: {}
      #/docker/*/blkio/io_queue_recursive/*/async: {}
      #/docker/*/blkio/io_queue_recursive/*/total: {}
      #/docker/*/blkio/io_service_time_recursive/*/read: {}
      #/docker/*/blkio/io_service_time_recursive/*/write: {}
      #/docker/*/blkio/io_service_time_recursive/*/sync: {}
      #/docker/*/blkio/io_service_time_recursive/*/async: {}
      #/docker/*/blkio/io_service_time_recursive/*/total: {}
      #/docker/*/blkio/io_wait_time_recursive/*/read: {}
      #/docker/*/blkio/io_wait_time_recursive/*/write: {}
      #/docker/*/blkio/io_wait_time_recursive/*/sync: {}
      #/docker/*/blkio/io_wait_time_recursive/*/async: {}
      #/docker/*/blkio/io_wait_time_recursive/*/total: {}
      #/docker/*/blkio/io_merged_recursive/*/read: {}
      #/docker/*/blkio/io_merged_recursive/*/write: {}
      #/docker/*/blkio/io_merged_recursive/*/sync: {}
      #/docker/*/blkio/io_merged_recursive/*/async: {}
      #/docker/*/blkio/io_merged_recursive/*/total: {}
      #/docker/*/blkio/io_time_recursive/*/read: {}
      #/docker/*/blkio/io_time_recursive/*/write: {}
      #/docker/*/blkio/io_time_recursive/*/sync: {}
      #/docker/*/blkio/io_time_recursive/*/async: {}
      #/docker/*/blkio/io_time_recursive/*/total: {}
      #/docker/*/blkio/sectors_recursive/*/read: {}
      #/docker/*/blkio/sectors_recursive/*/write: {}
      #/docker/*/blkio/sectors_recursive/*/sync: {}
      #/docker/*/blkio/sectors_recursive/*/async: {}
      #/docker/*/blkio/sectors_recursive/*/total: {}
      #/docker/*/connection/tcp/established: {}
      #/docker/*/connection/tcp/syn_sent: {}
      #/docker/*/connection/tcp/syn_recv: {}
      #/docker/*/connection/tcp/fin_wait1: {}
      #/docker/*/connection/tcp/fin_wait2: {}
      #/docker/*/connection/tcp/time_wait: {}
      #/docker/*/connection/tcp/close: {}
      #/docker/*/connection/tcp/close_wait: {}
      #/docker/*/connection/tcp/last_ack: {}
      #/docker/*/connection/tcp/listen: {}
      #/docker/*/connection/tcp/closing: {}
      #/docker/*/connection/tcp6/established: {}
      #/docker/*/connection/tcp6/syn_sent: {}
      #/docker/*/connection/tcp6/syn_recv: {}
      #/docker/*/connection/tcp6/fin_wait1: {}
      #/docker/*/connection/tcp6/fin_wait2: {}
      #/docker/*/connection/tcp6/time_wait: {}
      #/docker/*/connection/tcp6/close: {}
      #/docker/*/connection/tcp6/close_wait: {}
      #/docker/*/connection/tcp6/last_ack: {}
      #/docker/*/connection/tcp6/listen: {}
      #/docker/*/connection/tcp6/closing: {}
      #/docker/*/container/count: {}
      #/docker/*/container/running: {}
      #/docker/*/container/paused: {}
      #/docker/*/container/stopped: {}
      #/docker/*/cpu/cpu_usage/total: {}
      #/docker/*/cpu/cpu_usage/user_mode: {}
      #/docker/*/cpu/cpu_usage/kernel_mode: {}
      #/docker/*/cpu/cpu_usage/per_cpu/*/value: {}
      #/docker/*/cpu/throttling_data/nr_periods: {}
      #/docker/*/cpu/throttling_data/nr_throttled: {}
      #/docker/*/cpu/throttling_data/throttled_time: {}
      #/docker/*/cpu/cpu_shares: {}
      #/docker/*/cpuset/cpus: {}
      #/docker/*/cpuset/mems: {}
      #/docker/*/cpuset/memory_migrate: {}
      #/docker/*/cpuset/cpu_exclusive: {}
      #/docker/*/cpuset/memory_exclusive: {}
      #/docker/*/filesystem/*/device_name: {}
      #/docker/*/filesystem/*/type: {}
      #/docker/*/filesystem/*/capacity: {}
      #/docker/*/filesystem/*/usage: {}
      #/docker/*/filesystem/*/base_usage: {}
      #/docker/*/filesystem/*/available: {}
      #/docker/*/filesystem/*/inodes_free: {}
      #/docker/*/filesystem/*/reads_completed: {}
      #/docker/*/filesystem/*/reads_merged: {}
      #/docker/*/filesystem/*/sectors_read: {}
      #/docker/*/filesystem/*/read_time: {}
      #/docker/*/filesystem/*/writes_completed: {}
      #/docker/*/filesystem/*/writes_merged: {}
      #/docker/*/filesystem/*/sectors_written: {}
      #/docker/*/filesystem/*/write_time: {}
      #/docker/*/filesystem/*/io_in_progress: {}
      #/docker/*/filesystem/*/io_time: {}
      #/docker/*/filesystem/*/weighted_io_time: {}
      #/docker/*/hugetlb/*/usage: {}
      #/docker/*/hugetlb/*/max_usage: {}
      #/docker/*/hugetlb/*/failcnt: {}
      #/docker/*/memory/cache: {}
      #/docker/*/memory/usage/failcnt: {}
      #/docker/*/memory/usage/limit: {}
      #/docker/*/memory/usage/max_usage: {}
      #/docker/*/memory/usage/usage: {}
      #/docker/*/memory/usage/usage_percent: {}
      #/docker/*/memory/swap_usage/failcnt: {}
      #/docker/*/memory/swap_usage/limit: {}
      #/docker/*/memory/swap_usage/max_usage: {}
      #/docker/*/memory/swap_usage/usage: {}
      #/docker/*/memory/swap_usage/usage_percent: {}
      #/docker/*/memory/kernel_usage/failcnt: {}
      #/docker/*/memory/kernel_usage/limit: {}
      #/docker/*/memory/kernel_usage/max_usage: {}
      #/docker/*/memory/kernel_usage/usage: {}
      #/docker/*/memory/kernel_usage/usage_percent: {}
      #/docker/*/memory/statistics/total_inactive_anon: {}
      #/docker/*/memory/statistics/total_pgfault: {}
      #/docker/*/memory/statistics/total_pgmajfault: {}
      #/docker/*/memory/statistics/total_pgpgin: {}
      #/docker/*/memory/statistics/total_rss_huge: {}
      #/docker/*/memory/statistics/active_file: {}
      #/docker/*/memory/statistics/cache: {}
      #/docker/*/memory/statistics/total_active_file: {}
      #/docker/*/memory/statistics/working_set: {}
      #/docker/*/memory/statistics/pgmajfault: {}
      #/docker/*/memory/statistics/total_dirty: {}
      #/docker/*/memory/statistics/pgfault: {}
      #/docker/*/memory/statistics/total_unevictable: {}
      #/docker/*/memory/statistics/rss_huge: {}
      #/docker/*/memory/statistics/total_active_anon: {}
      #/docker/*/memory/statistics/total_mapped_file: {}
      #/docker/*/memory/statistics/writeback: {}
      #/docker/*/memory/statistics/active_anon: {}
      #/docker/*/memory/statistics/hierarchical_memory_limit: {}
      #/docker/*/memory/statistics/pgpgin: {}
      #/docker/*/memory/statistics/total_pgpgout: {}
      #/docker/*/memory/statistics/inactive_file: {}
      #/docker/*/memory/statistics/dirty: {}
      #/docker/*/memory/statistics/hierarchical_memsw_limit: {}
      #/docker/*/memory/statistics/rss: {}
      #/docker/*/memory/statistics/unevictable: {}
      #/docker/*/memory/statistics/pgpgout: {}
      #/docker/*/memory/statistics/total_cache: {}
      #/docker/*/memory/statistics/total_inactive_file: {}
      #/docker/*/memory/statistics/total_rss: {}
      #/docker/*/memory/statistics/total_swap: {}
      #/docker/*/memory/statistics/inactive_anon: {}
      #/docker/*/memory/statistics/swap: {}
      #/docker/*/memory/statistics/mapped_file: {}
      #/docker/*/memory/statistics/total_writeback: {}
      #/docker/*/network/*/rx_bytes: {}
      #/docker/*/network/*/rx_packets: {}
      #/docker/*/network/*/rx_errors: {}
      #/docker/*/network/*/rx_dropped: {}
      #/docker/*/network/*/tx_bytes: {}
      #/docker/*/network/*/tx_packets: {}
      #/docker/*/network/*/tx_errors: {}
      #/docker/*/network/*/tx_dropped: {}
      #/docker/*/pids/current: {}
      #/docker/*/pids/limit: {}
      #/docker/*/spec/status: {}
      #/docker/*/spec/creation_time: {}
      #/docker/*/spec/image_name: {}
      #/docker/*/spec/size_rw: {}
      #/docker/*/spec/size_root_fs: {}
      #/docker/*/spec/labels/*/value: {}

    publish:
      - plugin_name: publisher-appoptics
        config:
          period: 60
          floor_seconds: 60
